# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import data_viz
import update_data
from data_viz import vizmain


class mainwin(object):
    def openWindow(self):
        self.window = QtWidgets.QDialog()
        self.ui = data_viz.vizmain()
        self.ui.setupViz(self.window)
        self.window.show()

    def __init__(self):
        self.ui = None
        self.window = None
        self.viz_main = None
        self.upD = None
        self.label = None
        self.welcome = None
        self.main_screen = None

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1052, 810)
        self.main_screen = QtWidgets.QWidget(Dialog)
        self.main_screen.setGeometry(QtCore.QRect(10, 10, 1031, 791))
        self.main_screen.setStyleSheet("QWidget#main_screen{\n"
                                       "    font: 16pt \"MS Shell Dlg 2\";\n"
                                       "background-color:qlineargradient(spread:pad, x1:0, y1:0.00545455, x2:1, y2:1, "
                                       "stop:0 rgba(145, 135, 165, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.main_screen.setObjectName("main_screen")
        self.welcome = QtWidgets.QLabel(self.main_screen)
        self.welcome.setGeometry(QtCore.QRect(380, 30, 251, 51))
        self.welcome.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";color: White;")
        self.welcome.setObjectName("welcome")
        self.label = QtWidgets.QLabel(self.main_screen)
        self.label.setGeometry(QtCore.QRect(320, 90, 351, 41))
        self.label.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";color: white;")
        self.label.setObjectName("label")
        self.upD = QtWidgets.QPushButton(self.main_screen)
        self.upD.setGeometry(QtCore.QRect(350, 170, 251, 51))
        self.upD.setStyleSheet("border-radius:20px;\n"
                               "background-color: rgb(219, 212, 255);\n"
                               "font: 12pt \"MS Shell Dlg 2\";")
        self.upD.setObjectName("upD")
        self.viz_main = QtWidgets.QPushButton(self.main_screen)
        self.viz_main.setGeometry(QtCore.QRect(350, 270, 251, 51))
        self.viz_main.setStyleSheet("border-radius:20px;\n"
                                    "background-color: rgb(219, 212, 255);\n"
                                    "font: 12pt \"MS Shell Dlg 2\";")
        self.viz_main.setObjectName("viz_main")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.welcome.setText(_translate("Dialog", "IMD-Data"))
        self.label.setText(_translate("Dialog", "Please Select One of the Following:"))
        self.upD.setText(_translate("Dialog", "Update Data"))
        self.viz_main.setText(_translate("Dialog", "Visualize Data"))
