# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def __init__(self):
        self.welcome = None
        self.update_data = None

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1250, 790)
        self.update_data = QtWidgets.QWidget(Dialog)
        self.update_data.setGeometry(QtCore.QRect(9, 9, 1231, 771))
        self.update_data.setStyleSheet("QWidget#update_data{\n"
                                       "    font: 16pt \"MS Shell Dlg 2\";\n"
                                       "background-color:qlineargradient(spread:pad, x1:0, y1:0.00545455, x2:1, y2:1, "
                                       "stop:0 rgba(145, 135, 165, 255), stop:1 rgba(255, 255, 255, 255))}") 
        self.update_data.setObjectName("update_data")
        self.welcome = QtWidgets.QLabel(self.update_data)
        self.welcome.setGeometry(QtCore.QRect(210, 30, 821, 51))
        self.welcome.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";color: White;")
        self.welcome.setObjectName("welcome")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.welcome.setText(_translate("Dialog", "Welcome to IMD-Data - Update Tool"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
